# Generated by Django 2.2.1 on 2019-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('picture', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
    ]
